# Only put things in this file that we want in *every* environment
version: "3.9"

services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres:15-alpine # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

