version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./assets:/assets
      - ./images:/app/images
      - .env:/.env
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile